### ISSUE TITLE
Add land acknowledgement

### ISSUE THREAD

**Issue by UCGisWeek** [UCGisWeek/2020VirtualConference#11]

**Comment by UCGisWeek** [comment]
Hi Scott, we still need the text for this so it isn't as time-sensitive.  Thanks! Danielle

**Comment by UCGisWeek** [comment]
Add to about page

**Comment by albertkun** [comment]
"The organizers of the UC GIS Week conference wish to acknowledge that the UCs, as land grant institutions located on and benefiting from the dispossession of the original inhabitants from their lands, have a special responsibility to respect tribal sovereignty, amplify Native voices, and contribute to Native well-being in the state of California."

**Comment by UCGisWeek** [comment]
Posted!
