### ISSUE TITLE
Add general schedule to the main page

### ISSUE THREAD

**Issue by amywork20** [UCGisWeek/2020VirtualConference#14]
The general schedule for UC GIS Week 2020 (11/17-11/19) is:
Tuesday, Wednesday, Thursday
11am-12pm, 1pm-2pm and 3pm-4pm PT
With Mappy Lunch Hours 12:10-12:50pm PST each day for networking with your other UC colleagues

**Comment by UCGisWeek** [comment]
Added back the schedule link back in and moved the full schedule to it.  Used the schedule overview from the registration page.  Leaves us more room on the main page to add the rest of the content we wanted to add like slack.
