### ISSUE TITLE
About page - text needed

### ISSUE THREAD

**Issue by albertkun** [UCGisWeek/2020VirtualConference#15]

**Comment by albertkun** [comment]
The University of California GIS Week is put on by volunteers from the University of California campuses to help promote and inspire people to use mapping and geographic information sciences (GIS). 

The event is designed to be inclusive for people with no GIS background wanting to learn more, in addition to serving as a venue for making meaningful connections together. 

The UC GIS Week committee is made up of the following sub-committees:

Structuring- event programming 

Logistics- event planning and website

Marketing- outreach

If you are interested in learning more about the committee or would like to help with planning please reach out to ucgisweek@gmail.com.

**Comment by UCGisWeek** [comment]
Thank you - added 11/13
