### ISSUE TITLE
add land acknowledgment map

### ISSUE THREAD

**Issue by smpowell** [UCGisWeek/2020VirtualConference#37]
For our land acknowledgement map: here's the sample code snippet used in a workshop I recently attended which embeds a map from the Native Lands API. The lat/lon need to be updated to the appropriate center point, and of course the other style attributes can be edited, too.

<iframe src="https://native-land.ca/api/embed/embed.html?maps=territories&position=37.871853,-122.258423" width="100%" height="300px"></iframe>  Here it is in the context of the workshop: https://ubc-lib-geo.github.io/gis-workshop-waml-template/content/land-acknowledgement.html

**Comment by UCGisWeek** [comment]
iframe code has been added - will go live once we have the about text.

**Comment by UCGisWeek** [comment]
Can't set it to the state so it is set for LA
