### ISSUE TITLE
Add Slack information to site

### ISSUE THREAD

**Issue by UCGisWeek** [UCGisWeek/2020VirtualConference#4]

**Comment by amywork20** [comment]
During UC GIS Week, we will be using Slack as the main means of communicating. For live discussions and to send questions to moderators and presenters, join the new [UC GIS Slack](https://join.slack.com/t/ucgis/shared_invite/zt-iq0x0dzl-KlulnUoCFMkE24vNb5qv6A). Every UC GIS Week session has a channel, and there are also channels for general conversation and getting help.

Slack is a text chat tool available as a website and mobile app, where conversations happen in channels. [Here’s a guide to getting started with Slack](https://slack.com/resources/using-slack/your-quick-start-guide-to-slack).

**Comment by UCGisWeek** [comment]
Thank you for the text.! Added to index page on 11/6.
