### ISSUE TITLE
Debrah Oh's abstract needs to be updated

### ISSUE THREAD

**Issue by albertkun** [UCGisWeek/2020VirtualConference#40]
Should be the following:

Where we live influences health in both positive and negative ways. Interactive maps can provide researchers, policy makers, and public health professionals a better understanding of the relationship between place and health. The UCSF Health Atlas (healthatlas.ucsf.edu) is an online portal that visualizes social determinants of health as they relate to COVID-19 and other health outcomes in California. California Health Maps (californiahealthmaps.org) is an interactive mapping tool with cancer incidence at seven different geographic levels.

**Comment by UCGisWeek** [comment]
Updated!
